source "https://rubygems.org"

gem "rails", "4.2.4"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "devise"
gem "bootstrap-sass"
gem "bootstrap"
gem "cancancan"
gem "carrierwave"
gem "rmagick"
gem "sdoc", "~> 0.4.0", group: :doc

group :development, :test do
  gem "mysql2", "~> 0.3.18"
  gem "faker"
  gem "byebug"
  gem "pry"
end

group :development do
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "fabrication"
  gem "rspec-rails"
end
